
# Fast-exit for non-interactive shells
[[ -o interactive ]] || return

# 1. Environment & PATH -------------------------------------------------
export HOMEBREW_BUNDLE_DUMP_NO_VSCODE=1
export PATH="/opt/homebrew/bin:/opt/homebrew/opt/openssl@3/bin:$HOME/.local/bin:$PATH"

# Language / toolchains
export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$MODULAR_HOME/bin:$HOME/.cargo/bin:$HOME/.codeium/windsurf/bin:$HOME/.lmstudio/bin:$PATH"

# LS_COLORS (theme generated by vivid)
export LS_COLORS="$(vivid generate tokyonight-storm)"

# Load Cargo environment
# TODO: Move to using mise-en-place to handle this?
source "$HOME/.cargo/env"

# 2. Command line Completions -------------------------------------------
if command -v brew >/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
fi
autoload -Uz compinit && compinit   # run after FPATH is populated

# 3. Plugins / prompts --------------------------------------------------
eval "$(mise activate zsh)"
eval "$(zoxide init zsh)"            # must follow compinit for completions
eval "$(starship init zsh)"
eval "$(atuin init zsh)"

# 4. Aliases ------------------------------------------------------------
alias ll='lsd -al'
alias obs='open -u "obsidian://vault/$(basename "$(pwd)")"'

# 5. Functions ----------------------------------------------------------
title() { echo -ne "\033]1;$1\007"; }

# Terminal lines wrapping
wrap_on()  { printf '\e[?7h'; export WRAP_STATE="⮐"; }   # ESC[?7h  → wrap on
wrap_off() { printf '\e[?7l'; export WRAP_STATE="⮕"; }   # ESC[?7l  → wrap off

# ZLE widgets + key-bindings  (Ctrl-X w / Ctrl-X u)
zle -N wrap_on   ; bindkey '^Xw' wrap_on
zle -N wrap_off  ; bindkey '^Xu' wrap_off

# Shown in the promt (Starship.toml)
export WRAP_STATE="↩︎"   # default when the shell starts

# 6. History ------------------------------------------------------------
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000                # case-sensitive special variable
setopt APPEND_HISTORY         # don’t overwrite history file
setopt SHARE_HISTORY          # implies INC_APPEND_HISTORY
setopt EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST \
       HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_VERIFY

# 7. Misc ---------------------------------------------------------------
export JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION=true
# export PATH="$HOME/.composer/vendor/bin:$PATH"  # Laravel (optional)

# dotfiles repo helper. eg: dot status, dot add, dot commit. Only set when needed
dotfiles() {alias dot='git --git-dir=$HOME/.dotfiles --work-tree=$HOME'}
