palette = "tokyonight-custom"
add_newline = true 

format = """
$directory \
$git_branch$git_status\
$fill\
${env_var.WRAP_STATE} $time 
$character"""

[fill]
symbol = ' '

[character]
success_symbol = "❯"
error_symbol   = "[❯](bold fg:red)"

[directory]
truncation_length = 3        # keep three full segments
truncate_to_repo  = false    # don’t cut back to the repo root
fish_style_pwd_dir_length = 0  # 0 = disable fish-style abbreviations
truncation_symbol = "…/"
style   = "italic blue"
format  = '[$path]($style)'

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%b %-d %T"   # e.g. Jun 8, 2:05:33
utc_time_offset = "local"
style = "italic dimmed white"

[git_branch]
symbol = ""
format = "[[](fg:teal)$symbol $branch ]($style)"
style = "italic fg:white bg:teal"

[git_status]
format = "[($modified$staged$untracked)[ ](fg:teal)]($style)"
style = " bold italic fg:yellow bg:teal"
conflicted = "​"
untracked = "​?"
modified = "!​"
stashed = "≡"
deleted = "[✕](italic red)"

[env_var.WRAP_STATE]   # show terminal lines wrapping. Value set in .zshrc
variable = "WRAP_STATE"
format   = '[$env_value]($style)'
style    = 'dimmed yellow'

[palettes.tokyonight-custom]
mustard = '#af8700'
teal ='#28536A'
canvas = '#24283B'
grey = '#888888'